- name: Download nvm setup script
  become: no
  get_url:
    url: https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm.version }}/install.sh
    dest: "{{ ansible_env.HOME }}/src/nvm_setup_{{ nvm.version }}"

- name: Run nvm setup script
  become: no
  command:
    bash {{ ansible_env.HOME }}/src/nvm_setup_{{ nvm.version }}

- name: Setup nvm for zsh
  become: no
  with_items:
    - export NVM_DIR="$HOME/.nvm"
    - "[ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\"  # This loads nvm"
    - "[ -s \"$NVM_DIR/bash_completion\" ] && \\. \"$NVM_DIR/bash_completion\"  # This loads nvm bash_completion"
  lineinfile:
    create: yes
    path: "{{ ansible_env.HOME }}/.local_zshrc"
    line: "{{ item }}"
